### ISSUE TITLE
CCDData written as MEF FITs

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#196]
Since a CCDData object can include multiple planes (data, uncertainty, masks), it would be good if these could all be written out at the same time in order to save the data as a multi-extension FITS file

**Comment by mwcraig** [comment]
Weights also?

**Comment by MSeifert04** [comment]
I have been using something [like this](https://github.com/MSeifert04/pymsastro/blob/master/pymsastro/image/ndimage.py#L16) for a while now. If requested I could alter that so it fits the current [``CCDData.to_hdu``](https://github.com/astropy/ccdproc/blob/master/ccdproc/ccddata.py#L192). But I wasn't sure about some points - simply because I'm not very familiar with the FITS standards - and therefore refrained myself from suggesting something like this before.

**Comment by crawfordsm** [comment]
Okay I've spent some time reading through the [FITS standard](http://fits.gsfc.nasa.gov/fits_standard.html), and there doesn't seem to be any definition for how to handle masks or uncertainty frames.   So we are relatively free to do what we want.

I don't think in the 0.4 release we will handle MEF files that have multiple images in it, and I think they should be handled differently (and may end up being facility specific).  So I think we can set up something that would be the standard for saving a `CCDData` object.   

Regardless, what @MSeifert04 suggests was pretty much what i was thinking -- writing it out to an extension with the name of 'mask', 'uncertainty', or 'flag', and then being able to read those back in.  We do want this in `ccdproc` right now for the next release (and supported over various astropy versions), but I think having this in astropy as a reader/writer on NDData would be a great idea. 

Will you have tim this week to make a commit for that?   If not, I am hoping to do it by Tuesday, but it would be great to have one less thing to do.  

Also, I think it is okay to assume that uncertainty will have the same shape as data for right now and that it should throw an error if the uncertainty is something more complex.

**Comment by MSeifert04** [comment]
Yes, I do have some spare time and think I can make a commit later.
