### ISSUE TITLE
Overscan does not works with non-square images and axis != 1

### ISSUE THREAD

**Issue by wschoenell** [astropy/ccdproc#240]
I tried to do an `subtract_overscan` on a non-square image and got an error regarding the shape mismatch. To reproduce this I made this test:

	import numpy as np
	from astropy import units as u
	arr1 = ccdproc.CCDData(np.ones([100, 110]), unit=u.adu)
	no_scan = ccdproc.subtract_overscan(arr1, overscan=arr1[:, 90:100])
	no_scan = ccdproc.subtract_overscan(arr1, overscan=arr1[90:100], overscan_axis=0)

The first one works, the second raises:

	ValueError: operands could not be broadcast together with shapes (100,110) (110,1) 

The way I fixed it here is here: cfbf5e158bbd4239d09fd49605fc1c7bc5090b10.

**Comment by mwcraig** [comment]
Thanks for the report, @wschoenell. Are you interested into working up your solution into a pull request to fix it (mainly it would involve adding a test for the issue, which I can help you with)?

**Comment by wschoenell** [comment]
Yes, I can do it.

I just gave a quick look the tests and the image file that you use (`a8280271.fits`) is a square of 520 x 520 pixels (plus 16 px of overscan). Maybe changing the geometry of this image for a rectangle would help find bugs like this where the x, y different lengths are not take in account.

I did not deeply checked, but if you just change the shape of the test image, I believe that the existing test (see below) will comply with this bug.

https://github.com/astropy/ccdproc/blob/5481bb62f951d700ccbdf281351c8bb960908a98/ccdproc/tests/test_ccdproc.py#L88-L93

**Comment by mwcraig** [comment]
@wschoenell -- it turns out we are not actually using that image for most tests. Instead, for most tests we use the pytest fixture `ccd_data` defined at https://github.com/astropy/ccdproc/blob/master/ccdproc/tests/pytest_fixtures.py#L42

Probably the easiest way to change that test would, somewhere near the top of it, to change the size of `ccd_data` by slicing: `ccd_data.data = ccd_data.data[:, :-30]` (nothing special about the value 30).

I'd make that change first, make sure the test fails with the change, then add your fix.

Once this and a fix for #241 are in I think it makes sense to do another point release (0.3.2). Not quite ready yet for 0.4, but fixing these issues seems urgent.

Will talk to @crawfordsm on Tuesday, hoping to get a release out this week that fixes these problems.
