### ISSUE TITLE
Either more extensively test initialization of ImageFileCollection from a saved table or remove it

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#243]
This case hasn't been extensively tested...it should be, or maybe remove that part of it for now.

**Comment by MSeifert04** [comment]
I would be inclined to remove it in the future and maybe deprecate it for 1.3. 

It's really weird to use because the FileCollection from an info-file is not actually associated with any files, so it's just a partially functional `ImageFileCollection`. Given that we now allow a list of filenames (they have to be in the same directory) for the `__init__` that's probably much easier for us to use and less error-prone (in case the table is out-of-date).

**Comment by mwcraig** [comment]
Yeah, my original thinking with it had been that the location could be a URL and the info file would be a quick way of getting all of the image information without downloading all of the images. Then as one looped over images they would be downloaded as needed. But that use case would need more thought (are the files always saved to the working directory or some other one? what if the user doesn't set a save location? what happens if a connection is lost part way through a loop?), so I'm fine with deprecating.
