### ISSUE TITLE
Order of column names in ImageFileCollection is non-deterministic

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#262]
The reason is that the initial (ordered) list of keys is passed through a set (which is unordered) in https://github.com/astropy/ccdproc/blob/master/ccdproc/image_collection.py#L162-L168

Affects #258, among others...

**Comment by mwcraig** [comment]
And: https://github.com/astropy/ccdproc/blob/master/ccdproc/image_collection.py#L359-L360

And then (though note this is an `OrderedDict`): https://github.com/astropy/ccdproc/blob/master/ccdproc/image_collection.py#L375-L383

**Comment by evertrol** [comment]
Just an additional note, since I just stumbled upon this when deciphering the Travis failure for PR #263 : in the case where `_summayr_info` is assigned to an `astropy.table.Table` (https://github.com/astropy/ccdproc/blob/master/ccdproc/image_collection.py#L80-L84), the order of the `colnames` attribute is again indeterminate, since this is a list created from a the keys of a dict (https://github.com/astropy/astropy/blob/master/astropy/table/table.py#L1267).

This affects the doctest in docs/ccdproc/image_management.rst  at random.
