### ISSUE TITLE
Astropy header cards VerifyWarning

### ISSUE THREAD

**Issue by jmccormac01** [astropy/ccdproc#359]
Hi guys,
I get the following warnings from Astropy from several methods when reducing data with ccdproc. I don't think it is a major issue and it seems that astropy handles them? Just a heads up. 

Cheers
James

```
WARNING:astropy:VerifyWarning: Keyword name 'subtract_bias' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
```

```
WARNING:astropy:VerifyWarning: Keyword name 'subtract_dark' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
```

```
WARNING: VerifyWarning: Keyword name 'flat_correct' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
```

**Comment by mwcraig** [comment]
@jmccormac01 -- thanks for the report. These come up because the logging done by default in ccdproc adds a keyword whose name is the name of the routine that did the reduction, and fits doesn't allow keywords whose names are longer than 8 characters. I thought we had some mechanism for working around that, will look into it.

I assume you aren't doing anything custom with the logging?
