### ISSUE TITLE
Check if I can combine and rescale darks like this to build Master Darks of any exposure

### ISSUE THREAD

**Issue by sylvielsstfr** [astropy/ccdproc#360]
Hi,

I found very usefull your jupyter notebook on "ccdproc Example Reduction".
In it, you have darks corresponding to different exposure times which are similar to the exposure of science images.

In my case the darks were taken as a scan over exposure time from 1 second to 240 s.
My science images may not have their corresponding  sets of darks at the same exposure.
I should probably use all my statistics of darks to build a MasterDark.

Then I must use the linear time-scaling law of the darks (having their bias subtracted).

Could I do this time-re-scaling 

def MakeMasterDarkForExposureFromAll(master_darks_subbias,list_exposures,req_expo):
    '''
    Make a Master Dark for a required exposure time
    input : 
          all_master_darks_subbias : collection of darks having their bias subtracted
          list_exposures : list of exposure of the darks in all_master_darks_subbias
          req_expo : required exposure time
    output:
          the masterdark at the required exposure  
    '''

```
all_master_darks_exposcaled=[]  # output : a list of master-darks scaled for exposure req_expo
for chan in range(NB_OF_CHAN_AMPL): # loop over the number of CCD channels
    combined_master_darks_sb = [] 
    for idexp,expo in enumerate(list_exposures):  # loop over the exposures of the darks          
        timenormaliseddark=master_darks_subbias[chan][expo].multiply(req_expo/expo)   # rescale like this ?     
        combined_master_darks_sb.append(timenormaliseddark) 

    all_master_darks_exposcaled.append(ccdproc.Combiner(combined_master_darks_sb).average_combine())
return all_master_darks_exposcaled
```

Or should I give an array of rescaling-factor to the function average_combine(scale = thearray-of scaling-factor )

(is it the same ?)

Many thanks for your answer.

Sylvie

**Comment by mwcraig** [comment]
@sylvielsstfr -- let me start by restating the question just to make sure I understand it properly: Rather than choosing one of the darks and scaling that to the exposure time of the science image, you want to use all of the darks you have (which span a wide range of exposures) to create a single dark at the exposure time you need for the science image by scaling all of the individual darks to the same exposure time then averaging.

I think either approach, loop-and-multiply or array-of-scaling-factors will accomplish that.

Depending on the dark current and read noise of the CCD I would be a little careful about scaling the shortest exposures up to a longer exposure time. My CCD has high read noise (30 electrons) and fairly low dark current (~0.1 electron/px/sec). For short exposure times the darks are completely noise-dominated, and even for longer exposures I'm not entirely convinced we are actually measuring dark current (for most pixels, some are relatively hot).

You might start with a plot of the mean (or median) pixel value in each of the master darks as a function of their exposure time to see if that is linear.
