### ISSUE TITLE
How should create_deviation handle negative values

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#573]
While investigating #572 I've seen that the create_deviation function creates `nan`s where the data*gain + readnoise**2 is negative. That makes sense but currently the warning (from NumPy) just mentions "invalid value encountered in sqrt". I'm not sure if we shouldn't error out or provide a more informative warning in case (some of) the data is negative. Or if we should handle the pixels where the data is negative differently.

**Comment by crawfordsm** [comment]
I'd say plus one to a more informative error for the time being.   Otherwise, we might want to better handle the error creation with a clear definition of what it is doing and why it is doing it.  The equation is actually only appropriate for the case where data is large and a more complex calculation should be done for low count situations (however, my guess is that if it is a low count situation then background subtraction has already been done which should not be done prior to estimate the error)

**Comment by mwcraig** [comment]
We'll need to discuss this further....definitely the mininimum error should be the readnoise.

**Comment by mwcraig** [comment]
I'd say we raise an error with an explanation of how to suppress the error if that is appropriate (maybe a `disregard_nan` argument that defaults to `False`
