### ISSUE TITLE
too many files open

### ISSUE THREAD

**Issue by isobelsnellenberger** [astropy/ccdproc#629]
This is the template for bug reports, if you have a feature request or question
you can safely ignore and delete this prefilled text.

Include a description of the problem: What are you trying to do (include your
code and the **full** traceback)? What did you expect?
It's openning images multiple times instead of using the same image that is already open, so it's openning the same set of images 14 times instead of using the same image each time.

```python traceback
INFO:astropy:splitting each image into 14 chunks to limit memory usage to 1000000000.0 bytes.
INFO: splitting each image into 14 chunks to limit memory usage to 1000000000.0 bytes. [ccdproc.combiner]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    705         try:
--> 706             return obj.__dict__[self._key]
    707         except KeyError:

KeyError: 'data'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
~/miniconda3/envs/ast366/lib/python3.6/site-packages/reducer/gui.py in handler(b)
    563             self._go_button.disabled = True
    564             print(self)
--> 565             self.action()
    566 
    567             # change button should really only appear after the work is done.

~/miniconda3/envs/ast366/lib/python3.6/site-packages/reducer/astro_gui.py in action(self)
    471                 ("Processing {} of {} "
    472                  "(may take several minutes)".format(idx + 1, n_groups))
--> 473             combined = self._action_for_one_group(combo_group)
    474             name_addons = ['_'.join([str(k), str(v)])
    475                            for k, v in six.iteritems(combo_group)]

~/miniconda3/envs/ast366/lib/python3.6/site-packages/reducer/astro_gui.py in _action_for_one_group(self, filter_dict)
    521         combined = ccdproc.combine(file_list,
    522                                    mem_limit=DEFAULT_MEMORY_LIMIT,
--> 523                                    **combine_keyword_args)
    524 
    525         sample_image = ccdproc.CCDData.read(file_list[0])

~/miniconda3/envs/ast366/lib/python3.6/site-packages/ccdproc/combiner.py in combine(img_list, output_file, method, weights, scale, mem_limit, clip_extrema, nlow, nhigh, minmax_clip, minmax_clip_min, minmax_clip_max, sigma_clip, sigma_clip_low_thresh, sigma_clip_high_thresh, sigma_clip_func, sigma_clip_dev_func, dtype, combine_uncertainty_function, **ccdkwargs)
    758                     imgccd = image
    759                 else:
--> 760                     imgccd = CCDData.read(image, **ccdkwargs)
    761 
    762                 # Trim image

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/nddata/mixins/ndio.py in read(cls, *args, **kwargs)
     25         formats.
     26         """
---> 27         return io_registry.read(cls, *args, **kwargs)
     28 
     29     def write(self, *args, **kwargs):

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/io/registry.py in read(cls, format, *args, **kwargs)
    515 
    516         reader = get_reader(format, cls)
--> 517         data = reader(*args, **kwargs)
    518 
    519         if not isinstance(data, cls):

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/nddata/ccddata.py in fits_ccddata_reader(filename, hdu, unit, hdu_uncertainty, hdu_mask, hdu_flags, **kwd)
    499         # search for the first instance with data if
    500         # the primary header is empty.
--> 501         if hdu == 0 and hdus[hdu].data is None:
    502             for i in range(len(hdus)):
    503                 if hdus.fileinfo(i)['datSpan'] > 0:

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    706             return obj.__dict__[self._key]
    707         except KeyError:
--> 708             val = self.fget(obj)
    709             obj.__dict__[self._key] = val
    710             return val

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py in data(self)
    241             return
    242 
--> 243         data = self._get_scaled_image_data(self._data_offset, self.shape)
    244         self._update_header_scale_info(data.dtype)
    245 

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py in _get_scaled_image_data(self, offset, shape)
    707         code = BITPIX2DTYPE[self._orig_bitpix]
    708 
--> 709         raw_data = self._get_raw_data(shape, code, offset)
    710         raw_data.dtype = raw_data.dtype.newbyteorder('>')
    711 

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    473                               offset=offset)
    474         elif self._file:
--> 475             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    476         else:
    477             return None

~/miniconda3/envs/ast366/lib/python3.6/site-packages/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    293                     # file)
    294                     memmap = Memmap(self._file, mode=MEMMAP_MODES[self.mode],
--> 295                                     dtype=np.uint8)
    296 
    297                     # Now we immediately discard the memmap array; we are

~/miniconda3/envs/ast366/lib/python3.6/site-packages/numpy/core/memmap.py in __new__(subtype, filename, dtype, mode, offset, shape, order)
    277         elif (hasattr(filename, "name") and
    278               isinstance(filename.name, basestring)):
--> 279             self.filename = os.path.abspath(filename.name)
    280         # same as memmap copies (e.g. memmap + 1)
    281         else:

~/miniconda3/envs/ast366/lib/python3.6/posixpath.py in abspath(path)
    374             cwd = os.getcwdb()
    375         else:
--> 376             cwd = os.getcwd()
    377         path = join(cwd, path)
    378     return normpath(path)

OSError: [Errno 24] Too many open files
```

Don't forget to include the version of astropy, ccdproc and numpy, just copy
this into your Python interpreter (without the backticks):

```
import astropy
print(astropy.__version__)
import ccdproc
print(ccdproc.__version__)
import numpy
print(numpy.__version__)
```
astropy verson - 3.0.1
ccdproc version - 1.3.0
numpy version - 1.14.2

**Comment by mwcraig** [comment]
Thanks @isobelsnellenberger -- I'll take a look at this later today or tomorrow.

**Comment by mwcraig** [comment]
@isobelsnellenberger -- do you happen to remember what values you were using when combining (sigma clipping, combining method, etc)?

**Comment by isobelsnellenberger** [comment]
@mwcraig sigma clipping with a high and low threshold of both 5, average combination method

**Comment by mwcraig** [comment]
I believe I have figured out what the issue is here; a short summary is below. Wanted to write that before I start on tests then on code to fix.

I believe (though I have not yet checked) that addressing this issue will help address some of the performance issues with the `combine` function.

There are a couple of key things that affected this particular case:

- The underlying FITS files required no scaling. That means that (by default) when they are opened, they are opened as memory maps.
- Opening a memory map creates (at least briefly) *three* references to the file being opened:
    + One is created explicitly when the files is opened with, e.g. `fits.open`. This is the one you are probably already familiar with.
    + Two are created by Python's `mmap.mmap`, the underlying object used for memory maps. One is a "normal" file descriptor and the other is a reference to the file in the code's data. The OS (at least on Mac) counts those as two open files.
- There were enough images (100) that `combine` broke the operation into chunks.

One last thing I did not understand until a couple days ago: when a numpy array is created as a memory map you can close the file without affecting the memory map because the memory map retains its own references to the file.  That also means that when you "close" the file you are not actually removing all references to it.

To be absolutely explicit about it:

```python
fd = open(...)               # Number of open files increases by 1
MM = np.memmap(fd, mode='c') # Number of files open goes from 1 → 3 because memory mapped
fd.close()                   # Number of open files goes from 3 → 2 because we closed our file descriptor
del MM                       # Number of open files goes from 2 → 0 because reference count 
                             #     of MM goes to zero, and when all references to the map are 
                             #     gone the files are released.
```

I'll do a line-by-line analysis when I open a PR to fix this issue, but broadly this is what is happening:

+ The function `combine` loops over chunks.
+ On each iteration, each image is opened (via `CCData.read`),  by default FITS images are opened as memory maps, each `CCDData` object is sliced to get the working chunk, and the sliced CCDData is added to a list. That sliced `CCDData` is *not* in memory yet; it is a memory map
+ At the end of that list construction we have, for `N` files, `2N` file handles because each is a memory map.  There may be a couple more than that because intermediate variable like `imgccd` are still in scope and is a distinct object from the list of slices.
+ A `Combiner` object is created from the list of sliced `CCDData`; that increases the number of files open by another `N`, I think (or at least adds another reference to the memory maps that underly the slices).
+ Combination occurs.  `tile_combiner` is still in scope and has a reference to at least the list of CCD slices, which means it has a reference to the underlying memory maps, so the files are not closed.
+ The loop begins again. The list of slices is set to the empty list, but because `tile_combine` still has a reference to the list, the files are not closed; roughly `2N` files are open as far as the OS is concerned. 
+ As the list is recreated, new memory map objects are created; these result in an additional `N` files descriptors (am guessing that there is no new file in the code's data space, since the file name is already there), so at the end of loop creation there are `3N` files open (and the exception originally reported occurs).
+ A new `tile_combine` is created, releasing the last reference to the old list, which then releases the old memory map references, and the number of files open drops back to `2N`.

Incoming PR by the end of the day to fix this. I think it is also causing a pretty big performance overhead because we are repeatedly opening files when we don't need to (at least in the case when the files can be memory mapped).
