### ISSUE TITLE
cosmicray_lacosmic sepmed defaults to True

### ISSUE THREAD

**Issue by ysBach** [astropy/ccdproc#631]
Though it is not very clear, `cosmicray_lacosmic`'s [doc](http://ccdproc.readthedocs.io/en/latest/api/ccdproc.cosmicray_lacosmic.html#ccdproc.cosmicray_lacosmic) seems to say that it's default parameter values are set such that the default values for L.A. Cosmic by van Dokkum.

But to be so, the parameter `sepmed` should be `False`, since the original L.A. Cosmic does not have seperate median method.

**Comment by MSeifert04** [comment]
The `sepmed` is just a performance option (even though it could slightly change the results). 

What the documentation is trying to say is that the significant parameters (like sky subtraction, what limits, iterations) are the same by default. 

We probably shouldn't change the default value for `sepmed` because that makes the function significantly slower. And I'm not sure if changing the docs to reflect the difference in arguments would make things better. As end-user one is generally concerned about the PSF model, the clipping levels, the propagation, etc. not that the results may be slightly different because a separable median function was used that can be parallelized but doesn't give the correct median.

**Comment by jradavenport** [comment]
I'm working to make this change to the docs for my first astropy contribution
