### ISSUE TITLE
Preserving WCS with CCDProc and MEF files

### ISSUE THREAD

**Issue by katherinebruce529** [astropy/ccdproc#673]
I'm trying to preserve the WCS on some MEF files from KPNO using CCDProc and CCDData objects. (Trying to preserve it so after I flat correct I can combine the data into a single extension for photometry)

```python
file = 'flat2.fits'
flat = fits.getdata(file)
flat =CCDData(flat, unit=u.electron)
im = fits.getdata('n209767.fits')
im = CCDData(im, unit=u.electron)
reduced = ccdproc.flat_correct(im,flat)
reduced.write('data.fits')
```

I'm using Python 3.7.0, Astropy 3.1.2, CCDProc 1.3.0.post1, and Numpy 1.16.2

**Comment by mwcraig** [comment]
Thanks for the bug report, @katherinebruce529. I have a couple of questions just make sure I understand.

+ Is the file `flats.fits` a MEF, or just a single extension?
+ Is `n209767.fits` MEF, and 
+ if that is the MEF, is the desired outcome that flat be applied to each of the extensions, preserving all of the metada?

As a quick suggestion which may or may not let you do what you want immediately, I would use `CCDData.read` to get the data because that will pull in both the data and the FITS header, including the WCS.

That would look something like:

```python
from astropy.nddata import CCDData

file = 'flat2.fits'
flat = CCDData.read(file, unit=u.electron)

im = CCDData(i'n209767.fits', unit=u.electron)

reduced = ccdproc.flat_correct(im,flat)
reduced.write('data.fits')
```

**Comment by mwcraig** [comment]
Also opened https://github.com/astropy/astropy/issues/9043 as a reminder to improve documentation around working with FITS files.

**Comment by katherinebruce529** [comment]
Both the flat and the science image are MEF. Using CCDData.read did preserve the WCS, but only kept a single extension. I've got some other code to try to tinker with the other extensions, but thank you!

**Comment by mwcraig** [comment]
Ah, ok. What are the extensions in the MEF? Is each a different filter or is there a flat for each of the images in the science image?

**Comment by katherinebruce529** [comment]
There are 16 imageHDU extensions and a PrimaryHDU with the header. Each extension is a separate chip from the telescope, so the first extension on the flat corrects the first extension of the science image

**Comment by mwcraig** [comment]
Any chance you could send me a sample of each image?

**Comment by katherinebruce529** [comment]
They're way too big (even compressed) for me to attach them to this comment thread, is there a better way to send them?

**Comment by mwcraig** [comment]
There are a couple options; my email address is in my github profile (@mwcraig), maybe we could work out the details there?
