### ISSUE TITLE
ImageFileCollection not integrated into combine and Combiner

### ISSUE THREAD

**Issue by janerigby** [astropy/ccdproc#754]
The documentation for ccdproc's ImageFileCollection does not explain how to use ImageFileCollections to combine files. In addition, since ImageFileCollection works on a directory, the results of the method ImageFileCollection.files doesn't have the needed path.  As a result:
- `combine(image_collection.files)` fails with a `FileNotFoundError`.   
- `combine(image_collection.ccds` fails with `ValueError: unrecognised input for list of images to combine.`
- `Combiner(image_collection.ccds())` fails with `TypeError: object of type 'generator' has no len()`

How can one gather a bunch of fits files in ImageFileCollection, and then combine them with ccdproc.combine?  It almost seems like ImageFileCollection and combine/Combiner are two different packages that don't talk to each other.

**Comment by mwcraig** [comment]
@janerigby -- sorry for the delay in replying. You identified the historical issue here: `ImageFileCollection` was added a year or two after `Combiner` and `combine` and it is not clear how to use one with the other.

For working with the `combine` function there are a couple of options, because `combine` accepts a list of file names or a list of `CCDData` objects:

+ `combine(image_collection.files_filtered(include_path=True)`  should work. You can pass keyword arguments into `files_filtered` to get a subset of the files in the collection if you want. `include_path` is necessary if the files are in a different folder than the working directory. *If this does not work it is a bug, please comment here or open a separate issue.*
+ `combine([ccd for ccd in image_collection.ccds()])` should also work by generating a list of `CCDData` objects for processing. 

A similar trick works for `Combiner`:

+ `Combiner([ccd for ccd in image_collection.ccds()])` generates a list.

**I agree with you that `Combiner(image_collection.ccds())` should just work without the list comprehension in the two workarounds above.** Checking whether there is an issue for that one, and if not, opening one.
