### ISSUE TITLE
MNT: tags are inconsistent, some with "v", some without

### ISSUE THREAD

**Issue by pllim** [astropy/ccdproc#772]
If you look at https://github.com/astropy/ccdproc/tags , some tags have "v" prefix, some don't. Maybe it is too late to change the old tags now, but going forward, please pick one and stick with it. I don't think we need the "v" prefix.

**Comment by mwcraig** [comment]
I don't think I can fix the old ones -- or, rather, I'd prefer not to since they all have github releases and zenodo badges associated with them.

I did update the release instructions to make it clear that we shouldn't have a leading `v` anymore: https://github.com/astropy/ccdproc/wiki/Creating-a-new-release/_compare/b9849072e50eadaa0503724692e15cb74de6ed45

I'm closing as fixed, but please feel free to re-open if there is a better way to keep track of it.
